### ISSUE TITLE
Latest commit breaks plugin for me

### ISSUE THREAD

**Issue by jakobkhansen** [vimsence/vimsence#44] opened 2021-03-15 23:33 UTC
Hi,

I think latest commit breaks this plugin, see error:

```
Error detected while processing function DiscordUpdatePresence[1]..<SNR>61_InitializeDiscord[4]..provider
#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jakob/.config/nvim/plugged/vimsence/python/vimsence.py", line 39, in <module>
    with open('../vimsence.yaml', 'r') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: '../vimsence.yaml'
```

Already tried to do fresh install of plugin, does not fix this.

**Comment by hugolgst** [comment] 2021-03-16 06:31
@anned20 I think  we should always create PRs and never push to master directly. In order to avoid such things.
Could you move the current breaking commits to a new branch and revert them on master?

**Comment by hugolgst** [comment] 2021-03-16 08:22
I removed commits from master and added them to https://github.com/vimsence/vimsence/pull/45

**Comment by hugolgst** [comment] 2021-03-16 08:23
Sorry for that @jakobkhansen

**Comment by anned20** [comment] 2021-03-16 18:03
Reopening this, because I can't reproduce the error. 

What is your environment like? OS? NeoVim version?

**Comment by jakobkhansen** [comment] 2021-03-16 18:21
```
OS: Manjaro Linux
Neovim version: NVIM v0.5.0-dev+1133-g0869cbd55
```

It's definitely those commits, after reinstalling after the commits were removed these errors are gone.

**Comment by anned20** [comment] 2021-03-18 12:55
This should be fixed now, sorry for the inconveniences.

**Closed by anned20** 2021-03-18 12:55 UTC
